IF OBJECT_ID (N'[dbo].[Client]', N'U') IS NULL
BEGIN
	CREATE TABLE Client
	(
		Id int IDENTITY(1,1) PRIMARY KEY,
		ClientCode NVARCHAR(50) NULL,
		ClientName NVARCHAR(100) NULL,
		APIKey NVARCHAR(MAX) NULL,
		IsActive BIT NOT NULL,
		CreatedDateTime DATETIME DEFAULT(GETUTCDATE()) NOT NULL,
		UpdatedDateTime DATETIME DEFAULT(GETUTCDATE()) NOT NULL,
		LastAccessedDateTime DATETIME NULL
	)
END